/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthModal: typeof import('./../components/AuthModal.vue')['default']
    EditProfileModal: typeof import('./../components/EditProfileModal.vue')['default']
    PostCard: typeof import('./../components/PostCard.vue')['default']
    PostDetailModal: typeof import('./../components/PostDetailModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
