server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:simplenote_db}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      timeout: 2s
    
  # ================= 新增：打破体型封印，允许上传大图 =================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# =================  MyBatis 配置 =================
mybatis:
  configuration:
    # 开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    # 在控制台打印执行的 SQL 语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  charset:
    console: UTF-8
    file: UTF-8
  level:
    "[com.simplenote.backend]": TRACE
    "[org.springframework.web]": DEBUG
    root: INFO
    "[org.springframework.web.servlet.mvc.method.annotation.SseEmitter]": TRACE

file:
  upload-dir: uploads/

cache:
  post:
    detail-ttl: 30m
    null-ttl: 5m

social:
  sync:
    fixed-delay-ms: 10000
